version: '3'
services:
    redis:
        image: redis:latest
        container_name: redis-local
        ports:
            - 6379:6379
        # volumes:
            # - ./config/redis.conf:/redis.conf
        # command: [ "redis-server", "/redis.conf" ]

    redis-commander:
        ## https://github.com/joeferner/redis-commander?tab=readme-ov-file
        container_name: redis-commander
        # hostname: redis-commander
        image: ghcr.io/joeferner/redis-commander:latest
        restart: always
        environment:
        - REDIS_HOSTS=local:redis:6379
        - PORT=6389
        ports:
        - "6389:6389"
